@startuml
'https://plantuml.com/class-diagram

class Player

class Game {
    * Player
    * Region
    * WorldMap
    --
    play()
    render()
}
class WorldMap {
    * tiles
    --
    render()
}
class Tile {
    * index
    --
    * region
    getNeighbor()
}

WorldMap }|--|| Tile
Region |o-- Player
Game ||--|| WorldMap
Game ||--|{ Player
Game ||--|{ Region
Region ||--|{ Tile
@enduml